routes/web.php
<?php

Route::get('/', function () {
	return view('welcome');
});

Route::get('getip',function(){
	$ch = curl_init ();
      // set URL and other appropriate options
	curl_setopt ($ch, CURLOPT_URL, "http://ipecho.net/plain");
	curl_setopt ($ch, CURLOPT_HEADER, 0);
	curl_setopt ($ch, CURLOPT_RETURNTRANSFER, true);

      // grab URL and pass it to the browser

	$ip = curl_exec ($ch);
	echo "The public ip for this server is: $ip";
      // close cURL resource, and free up system resources
	curl_close ($ch);

	$ip= \Request::ip();
	 // exit;
  	//   $ip= "103.195.248.111";
	$data = \Location::get($ip);
	dd($data);
});

Route::get('/merit', 'AdmissionOpenController@generateMeritList');		
Route::get('/confirm_admission', 'AdmissionOpenController@generateConfirmList');		
Route::get('/payment_settle', 'AdmissionOpenController@generatePaymentSettled');		

Auth::routes();

Route::get('test', 'HomeController@test');
Route::get('print_test', 'HomeController@printTest');
Route::get('admission_document', 'AdmissionOpenController@admissionDocument');
Route::get('admission_open_id', 'AdmissionOpenController@admissionOpenId');
//************* Step 1 Email Verify ***************//
Route::group(array('prefix' => 'school/email-verify/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@emailVerifyView');	
	Route::get('/re-send-email', 'Auth\SchoolStepsController@resendEmail');		
	Route::post('account/update', 'Auth\SchoolStepsController@emailVerifyUpdate');
});

//************* Step 2 Account Payment Verify ***************//
Route::group(array('prefix' => 'school-profile-review/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@reviewVerifyView');	
});

//************* Step 3 Profile Verify ***************//
Route::group(array('prefix' => 'school-profile-verify/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@schoolProfileVerifyView');	
	Route::post('update', 'Auth\SchoolStepsController@schoolProfileVerifyUpdate');
	//Route::get('account/verify', 'SchoolProfileController@schoolEmailVerifyFirst');	
	//Route::get('account/verify/hq', 'SchoolProfileController@schoolEmailVerifySecond');	
});

//************* Step 4 Course Selections ***************//
Route::group(array('prefix' => 'course-selections/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@schoolCourseVerifyView');	
	Route::post('update/{schoolprofileid}', 'Auth\SchoolStepsController@schoolCourseSelectionVerifyUpdate');
});

Route::get('/home', 'DashboardController@dashboard');
Route::get('/', 'DashboardController@dashboard');

Route::group(array('prefix' => 'account/'), function() {
	Route::get('verify', 'SchoolProfileController@schoolEmailVerifyFirst');	
	Route::get('verify/hq', 'SchoolProfileController@schoolEmailVerifySecond');	
	Route::post('verify/otp', 'SchoolProfileController@schoolEmailVerifyUpdate');
});

Route::group(array('prefix' => 'school/'), function() {
	Route::post('account/auth/profile', 'SchoolProfileController@step1Update');
	Route::get('account/profile', 'Auth\AuthSchoolController@step1');	
	Route::get('account/review', 'Auth\AuthSchoolController@step2');	
	Route::get('account/payment', 'Auth\AuthSchoolController@step3');	
	Route::post('account/payment/pay', 'PaymentController@schoolFirst');	
	Route::get('review-confirmation', 'SchoolProfileController@reviewConfirmation');
	//Route::get('account/verify/hq', 'SchoolProfileController@schoolEmailVerifySecond');	
});

Route::group(array('prefix' => 'payment/'), function() {
	Route::get('confirm_payment', 'PaymentController@confirmPayment');
	Route::get('confirm_payment/{admissionId}/view', 'PaymentController@confirmPaymentView');
});

Route::group(array('prefix' => 'course/'), function() {
	Route::get('{course_hash}/details', 'CourseController@courseView');
	Route::get('eligibility/{linkId}/list', 'CourseController@eligibilityList');
	Route::post('eligibility/deleted', 'CourseController@eligibilityDelete');
	Route::post('eligibility/disabled', 'CourseController@eligibilityDisable');
	Route::post('eligibility/eligibilitystore', 'CourseController@eligibilityStore');

	Route::get('syllabus/{linkId}/list', 'CourseController@syllabusList');
	Route::post('syllabus/store', 'CourseController@syllabusStore');
	Route::post('syllabus/update', 'CourseController@syllabusUpdate');
	Route::post('syllabus/deleted', 'CourseController@syllabusDelete');
	
	Route::post('syllabus/disabled', 'CourseController@syllabusDisable');
	Route::post('tab1/update/{linkId}', 'CourseController@courseDetailsUpdate');
	Route::post('tab2/update/{linkId}', 'CourseController@eligibilityUpdate');
	Route::post('syllabus/update/{linkId}', 'CourseController@syllabusUpdate');
	Route::post('status', 'CourseController@status');
}); 

Route::group(array('prefix' => 'admission/'), function() {
	Route::get('status', 'AdmissionOpenController@admissionStatus');
	Route::get('transaction', 'AdmissionOpenController@transaction');

	Route::get('live_search/action', 'AdmissionOpenController@action')->name('live_search.action');

	Route::get('transactionapi', 'AdmissionOpenController@transactionapi');
	Route::get('transaction/{id}/view', 'AdmissionOpenController@transactionDetails');	
	Route::get('transaction/academicdetails', 'AdmissionOpenController@academicDetails');	
	Route::get('create/{linkId}', 'AdmissionOpenController@admissionOpen'); 
	Route::get('open/list', 'AdmissionOpenController@admissionCreateList'); 	
	Route::get('create/{id}/detail', 'AdmissionOpenController@admissionDetail');
	Route::get('detail/list/{id}', 'AdmissionOpenController@admissionDetailList');
	Route::post('open/update', 'AdmissionOpenController@admissionOpenUpdate'); 	
	Route::get('merit-list','AdmissionOpenController@meritList');
	Route::get('documents','AdmissionOpenController@admissionDocuments');
	Route::get('confirm','AdmissionOpenController@admissionConfirm');
	Route::get('confirm/d','AdmissionOpenController@admissionConfirmDetail');
	Route::post('documents/confirm','AdmissionOpenController@admissionDocumentsConformStatus');
	Route::post('documents/cancelled','AdmissionOpenController@admissionDocumentsCancelledStatus');
}); 

Route::group(array('prefix' => 'users/'), function() {
	Route::post('status', 'UserController@statusUser');
});

Route::group(array('prefix' => 'faculty/'), function() {
	Route::post('status', 'FacultyController@statusFaculty');
	Route::post('list', 'FacultyController@show');
	Route::post('deleted', 'FacultyController@deleteGallery');
	Route::post('disabled', 'FacultyController@disableGallery');
});

Route::group(array('prefix' => 'settings/'), function() {
	Route::get('security', 'SettingController@securityIndex');
	Route::get('privacy', 'SettingController@privacyIndex');
	Route::get('notifications', 'SettingController@notifications');
	Route::post('general/edit', 'SettingController@generalSettingEdit');
	Route::post('general/update', 'SettingController@generalSettingUpdate');
	Route::get('changePassword','HomeController@showChangePasswordForm');
	Route::post('changePassword','HomeController@changePassword')->name('changePassword');    
});

Route::group(array('prefix' => 'profile/'), function() {
	Route::post('update', 'ProfileController@update');	 	 
	Route::post('up/banner', 'ProfileController@schoolBannerImage');	 	 
	Route::post('up/logo', 'ProfileController@schooLogoImage');	 	 
}); 

Route::group(array('prefix' => 'enrolments/'), function() {
	Route::get('update', 'EnrolmentController@update');	 
	Route::get('enrollmentList', 'EnrolmentController@enrollmentList');	 
	Route::get('{courseid}/list', 'EnrolmentController@list');	 
	Route::get('{courseid}/listapi', 'EnrolmentController@listapi');	 
	Route::get('{courseid}/upload', 'EnrolmentController@upload');
	Route::get('{courseid}/{id}/edit', 'EnrolmentController@listEdit');
	Route::post('deleted', 'EnrolmentController@enrollmentDelete');	 
}); 

Route::group(array('prefix' => 'gallery/'), function() {
	Route::post('list', 'GalleryController@show');	 
	Route::post('upload', 'GalleryController@upload');	 
	Route::post('deleted', 'GalleryController@deleteGallery');	 
	Route::post('disabled', 'GalleryController@disableGallery');	 
}); 

Route::group(array('prefix' => 'enquiry/'), function() {
	Route::get('list', 'EnquiryController@show');	 
}); 

Route::group(array('prefix' => 'bank/'), function() {
	Route::get('list', 'BankController@list');	 
}); 

Route::resource('course', 'CourseController');
Route::resource('admission', 'AdmissionOpenController');
Route::resource('users', 'UserController');
Route::resource('enrolments', 'EnrolmentController');
Route::resource('roles', 'RoleController');
Route::resource('faculty', 'FacultyController');
Route::resource('permissions', 'PermissionController');
Route::resource('payments/ad', 'PaymentController');
Route::resource('bank', 'BankController');
Route::resource('all-activity', 'ActivityController');
Route::resource('settings', 'SettingController');
Route::resource('gallery', 'GalleryController');
Route::resource('profile', 'ProfileController');

Route::post('schoolDetailUpdate/update', 'SchoolController@schoolDetailUpdate')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'otp', 'user_hash' ,'user_role', 'email_verify', 'payment_verify', 'profile_verify','user_role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/SchoolController.php
<?php   
namespace App\Http\Controllers;
use Auth;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Model\TempSchoolProfile;
use App\Model\User;
use Session;
use DB;

class SchoolController extends Controller
{
   public function __construct(){

   	$this->middleware('auth');
   }
   
   public function index(){


      $userId = Auth::user()->id;  

      $schoolProfile = DB::table('temp_school_profile')
         ->join('users', 'temp_school_profile.user_id', '=', 'users.id')
         ->where('users.id',$userId)
         ->first();       

      return view('temp_school_profile',compact('schoolProfile'));
    }

   public function pendingSchoolIndex(){

      $userId = Auth::user()->id;
      
      $q = TempSchoolprofile::query();

      $q->whereHas('user', function($query) use ($userId) {
         $query->where('id', $userId);
         $query->where('user_status', getenv('STATUS_11'));
      });
      $q->with('state');

      $schoolData = $q->get()->toArray();

      return view('school.school_registration.index',compact('schoolData'));
   }

   public function pendingSchoolView(Request $request,$id){

      $userId = Auth::user()->id;
      
      $schoolData = TempSchoolProfile::with('state')->where('id',$id)->first()->toArray();
      return view('school.school_registration.view',compact('schoolData'));
   }

   public function activeSchoolIndex(){
      $userId = Auth::user()->id;
      $q = TempSchoolprofile::query();
      $q->whereHas('user', function($query) use ($userId) {
         $query->where('id', $userId);
         $query->where('user_status', getenv('STATUS_22'));
      });
      $q->with('state');
      $schoolData = $q->get()->toArray();
      return view('school.school_active.index',compact('schoolData'));
   }

   public function activeSchoolView(Request $request,$id){
      $userId = Auth::user()->id;
      $schoolData = TempSchoolProfile::with('state')->where('id',$id)->first()->toArray();
      return view('school.school_active.view',compact('schoolData'));
   }

   public function schoolApprove(Request $request){

      $userId = Auth::user()->id;

      $post = $request->all();     

      $data = User::where('id',$post['user_id'])->first();        

      $data->user_status = getenv('STATUS_22');

      $data->save();

      return redirect('pending-school')->with('success','School approved successfully')   ;

   }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\SubUser;
use App\Model\User;
use Auth;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

//Enables us to output flash messaging
use Session;

class UserController extends Controller {

    public function __construct() {

        // $this->middleware(['auth', 'isAdmin','CheckUserStatus']); //isAdmin middleware lets only users with a //specific permission permission to access these resources       
    }
    
    public function index() {        
        $users = User::orderBy('id', 'desc')->paginate(10); 
        $role = Role::all();
        $p = Permission::all();       
        // $permissions = $user->permissions;
        $usersdata = SubUser::with('userdata')->where('school_id',Session::get('school_id'))->get()->toArray();

        return view('school.users.index',['users'=>$users,'permissions'=>$p,'roles'=>$role,'usersdata'=>$usersdata]);
    }
   
    public function create() {        
        $roles = Role::get();
        return view('school.users.create', ['roles'=>$roles]);
    }
   
    public function store(Request $request) 
    {
        $post = $request->all();
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:4|confirmed',
            'roles'=>'required|array'
        ]);      

        $post['user_role'] = 'SU';
        $post['user_status'] = 2;        
        $user = User::create($post);    
        $user->user_hash = bcrypt($user->id);     
        $user->save();

        //---------For Sub User data store
        $subUser['school_id'] = 149;  
        $subUser['master_user_id'] = Auth::user()->id;  
        $subUser['user_id'] = $user->id;
        SubUser::create($subUser);

        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {
            foreach ($roles as $role) {
                $role_r = Role::where('id', '=', $role)->firstOrFail();            
                $user->syncRoles($role_r); //Assigning role to user
            }
        }

        $data = [
                    'email' =>  'sksuthar09@gmail.com',
                    'password' => 'ddd',
                    'link'=> url("/payment-online/"),
                    'school_name' => 'sinhgad'
                ];
                $email = $request->email;
                

       
        return redirect()->route('users.index')
            ->with('success_message','User successfully added.');
    }
    
    public function show($id) {
        return redirect('users'); 
    }

    public function edit($id) {
        $user = User::findOrFail($id); //Get user with specified id
        $roles = Role::get(); //Get all roles

        return view('school.users.edit', compact('user', 'roles')); //pass user and roles data to view
    }
    
    public function update(Request $request, $id) {
        $user = User::findOrFail($id); //Get role specified by id
        
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users,email,'.$id,
            // 'password'=>'required|min:6|confirmed'
        ]);
        $input = $request->only(['name', 'email']); //Retreive the name, email and password fields
        $roles = $request['roles']; //Retreive all roles
        $user->fill($input)->save();

        if (isset($roles)) {        
            $user->roles()->sync($roles);  //If one or more role is selected associate user to roles          
        }        
        else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        return redirect()->route('users.index')->with('success_message','User successfully edited.');
    }

    public function statusUser(Request $request){
        $post = $request->all();
        $validator = \Validator::make($post, ['_token'=>'required','user_hash'=>'required']);

        if ($validator->fails()) {
            return response()->json([
                    'status' => '202',
                    'message' => $validator->messages()
            ]);
        }

        $user = User::where('user_hash',$post['user_hash'])->first();            
        if(!empty($user)){
            $user->user_status = ($user->user_status==1) ? 2 : 1;
            $user->save();    
        }           
        
        if(isset($user->id)){
            return response()->json([
                  'status' => 'true',
                  'code'=>'200',
                  'message' =>'successfully updated'
               ]);      
        }else{
            return response()->json([
                  'status' => 'false',
                  'code'=>'202',
                  'message' =>'Something went wrong1'
               ]);  
        }
        
    }
    public function destroy($id) {
        //Find a user with a given id and delete
        $user = User::findOrFail($id); 
        $user->delete();

        return redirect()->route('users.index')
            ->with('flash_message',
             'User successfully deleted.');
    }
}

resources/views/school/users/create.blade.php
@extends('layouts.app')

@section('title', '| Add User')

@section('content')
<section class="content"> 
    <div class="row">                                                      
        <div class="offset-3 col-md-5">
            <div class="card mb-5">
                <div class="card-body">
                    <span class="card-title"><i class="fa fa-user-plus pr-2" aria-hidden="true"></i><strong>Add User</strong></span>                             
                    <div class="">  
                        <div class="">
                            {{ Form::open(array('url' => 'users')) }}
                                <div class="md-form form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                    {{ Form::label('name', 'Name *') }}
                                    {{ Form::text('name', '', array('class' => 'form-control mb-0')) }}
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="md-form form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                    {{ Form::label('email', 'Email *') }}
                                    {{ Form::email('email', '', array('class' => 'form-control mb-0')) }}
                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <h5><b>Give Role *</b></h5>
                                <div class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                                    @foreach ($roles as $role)
                                        {{ Form::checkbox('roles[]',  $role->id ) }}
                                        {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                                    @endforeach
                                    @if ($errors->has('roles'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('roles') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="md-form form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                    {{ Form::label('password', 'Password *') }}
                                    {{ Form::password('password', array('class' => 'form-control mb-0')) }}
                                    @if ($errors->has('password'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="md-form form-group mt-0">
                                    {{ Form::label('password', 'Confirm Password *') }}
                                    {{ Form::password('password_confirmation', array('class' => 'form-control mb-0')) }}
                                </div>
                                 <div class="md-form form-group m-0">
                                    {{ Form::submit('Add', array('class' => 'btn btn-primary btn-sm mr-2 m-0')) }}
                                    <a href="{{ url('/users')}}" class="btn btn-outline-secondary btn-sm m-0">Back</a>
                                </div>
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/school/users/index.blade.php
@extends('layouts.app')

@section('title', '| Users')

@section('content')
<section class="content">                                                     
        <div class="">
            <div class="mdc-top-app-bar__title">Users List</div>
            @if(Session::get('success_message'))
                <div class="alert alert-success" role="alert"><strong>Success!</strong>&nbsp;&nbsp;{{Session::get('success_message')}}</div>
            @endif 
            @if(Session::get('error_message'))
                <div class="alert alert-success" role="alert">{{Session::get('success_message')}}</div>
            @endif 
            <div class="card mb-5">
               <div class="card-body"><!-- 
                    <div class="">                   
                    <i class="fa fa-users" aria-hidden="true"></i>
                     <span class="card-title"><strong>Users List</strong></span>                             
                    </div> -->
                    <div class="card-body p-0">  
                        <div class="">
                            <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm pull-left"><i class="fa fa-plus pr-2"></i>Add User</a>
                            <a href="{{ route('roles.index') }}" class="btn btn-default btn-sm pull-right"><i class="fa fa-users pr-2"></i>Roles</a>
                            <a href="{{ route('permissions.index') }}" class="btn btn-warning btn-sm mr-2 pull-right"><i class="fa fa-shield pr-2"></i>Permissions</a>                        
                            <div class="table-responsive">                            
                                <table class="table table-bordered table-hover mt-3">
                        
                                    <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Date/Time Added</th>
                                            <th>User Roles</th>
                                            <th>Operations</th>
                                        </tr>
                                    </thead>
                                    <tbody>         
                                        @if(!empty($usersdata))
                                        @foreach ($usersdata as $value)
                                            @foreach ($users as $user)
                                                @if($value['userdata']['id']==$user->id)
                                                <tr>
                                                    <td>{{ $user->name }}</td>
                                                    <td>{{ $user->email }}</td>
                                                    <td>{{ $user->created_at->format('F d, Y h:ia') }}</td>
                                                    <td><span class="badge badge-info ml-2">{{  $user->roles()->pluck('name')->implode(' , ') }}</span></td>
                                                    <td style="width: 157px;">
                                                    <a href="{{ route('users.edit', $user->id) }}" class="btn btn-outline-grey btn-sm pull-left mr-2 m-0"><i class="fa fa-pencil"></i></a>

                                                    <!-- {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id] ]) !!}
                                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-sm pull-right']) !!}
                                                    {!! Form::close() !!} -->
                                                    @if($user->user_status==1)
                                                      <button type="button" class="btn btn-outline-danger  btn-sm user-status m-0" data-toggle="modal" data-user-hash="{{$user->user_hash}}" data-user-name="{{ $user->email }}" data-target="#statusUserModal"> <i class="fa fa-times" aria-hidden="true"></i></button>
                                                    @else

                                                      <button type="button" class="btn btn-outline-success  btn-sm user-status m-0" data-user-hash="{{$user->user_hash}}" data-user-name="{{ $user->email }}" data-toggle="modal" data-target="#statusUserModal">  <i class="fa fa-check" aria-hidden="true"></i>  </button>
                                                      @endif

                                                    </td>
                                                </tr>
                                                @endif
                                            @endforeach
                                        @endforeach
                                        @else
                                            <tr>
                                                <td colspan="5">
                                                    <center>
                                                        <div class="alert alert-warning mt-4" role="alert"><strong>No User created yet!</strong></div>
                                                    </center>
                                                </td>
                                            </tr>
                                        @endif
                                    </tbody>
                                </table>
                                {{ $users->links() }}
                            </div>                       
                        </div>
                    </div>
                </div>
            </div>
        </div>    
</section>
<div class="modal" id="statusUserModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Confirm</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>                  
            <form name="userUpdateForm" id="userUpdateForm" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="alert model-message" role="alert" style="display: none;">     
                </div>            
                    <label>Are you sure want to change status of user&nbsp;<strong><span class="user-name">&nbsp;</span></strong>?</label>                     
                        {!! csrf_field() !!}
                        <input type="hidden" name="user_hash" class="user-hash">                    
                </div>            
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-sm user-status-btn">Submit</button>
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $(".user-status").click(function(){        
        var userHash = $(this).data("user-hash");
        var userName = $(this).data("user-name");
        $(".user-hash").val(userHash);     
        $(".user-name").text(userName);     
   });  

   $(".user-status-btn").click(function(){           
      var form = $("[name=userUpdateForm]");
      form.validate({
        ignore: "",        
        submitHandler: function()
        {
            formdata=$("#userUpdateForm").serialize();
            $.ajax({
               type: "POST",
               url: "{{ url('users/status') }}",
               data: formdata,
               success: function (result){    
                  if(result.code=='200'){                     
                    $(".model-message").show();            
                    $(".model-message").text(result.message);                                      
                    $(".model-message").addClass('alert-success');                                      
                     window.location.reload(4000);
                  }else{
                    $(".model-message").show();
                    $(".model-message").text(result.message);                                      
                    $(".model-message").addClass('alert-danger'); 
                    window.location.reload(4000);                                      
                  }
               }
            });
         } 
      });
   }); 
});
</script>
@endsection