routes/web.php
<?php

Route::get('/', function () {
	return view('welcome');
});

Route::get('getip',function(){
	$ch = curl_init ();
      // set URL and other appropriate options
	curl_setopt ($ch, CURLOPT_URL, "http://ipecho.net/plain");
	curl_setopt ($ch, CURLOPT_HEADER, 0);
	curl_setopt ($ch, CURLOPT_RETURNTRANSFER, true);

      // grab URL and pass it to the browser

	$ip = curl_exec ($ch);
	echo "The public ip for this server is: $ip";
      // close cURL resource, and free up system resources
	curl_close ($ch);

	$ip= \Request::ip();
	 // exit;
  	//   $ip= "103.195.248.111";
	$data = \Location::get($ip);
	dd($data);
});

Route::get('/merit', 'AdmissionOpenController@generateMeritList');		
Route::get('/confirm_admission', 'AdmissionOpenController@generateConfirmList');		
Route::get('/payment_settle', 'AdmissionOpenController@generatePaymentSettled');		

Auth::routes();

Route::get('test', 'HomeController@test');
Route::get('print_test', 'HomeController@printTest');
Route::get('admission_document', 'AdmissionOpenController@admissionDocument');
Route::get('admission_open_id', 'AdmissionOpenController@admissionOpenId');
//************* Step 1 Email Verify ***************//
Route::group(array('prefix' => 'school/email-verify/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@emailVerifyView');	
	Route::get('/re-send-email', 'Auth\SchoolStepsController@resendEmail');		
	Route::post('account/update', 'Auth\SchoolStepsController@emailVerifyUpdate');
});

//************* Step 2 Account Payment Verify ***************//
Route::group(array('prefix' => 'school-profile-review/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@reviewVerifyView');	
});

//************* Step 3 Profile Verify ***************//
Route::group(array('prefix' => 'school-profile-verify/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@schoolProfileVerifyView');	
	Route::post('update', 'Auth\SchoolStepsController@schoolProfileVerifyUpdate');
	//Route::get('account/verify', 'SchoolProfileController@schoolEmailVerifyFirst');	
	//Route::get('account/verify/hq', 'SchoolProfileController@schoolEmailVerifySecond');	
});

//************* Step 4 Course Selections ***************//
Route::group(array('prefix' => 'course-selections/'), function() {		
	Route::get('/', 'Auth\SchoolStepsController@schoolCourseVerifyView');	
	Route::post('update/{schoolprofileid}', 'Auth\SchoolStepsController@schoolCourseSelectionVerifyUpdate');
});

Route::get('/home', 'DashboardController@dashboard');
Route::get('/', 'DashboardController@dashboard');

Route::group(array('prefix' => 'account/'), function() {
	Route::get('verify', 'SchoolProfileController@schoolEmailVerifyFirst');	
	Route::get('verify/hq', 'SchoolProfileController@schoolEmailVerifySecond');	
	Route::post('verify/otp', 'SchoolProfileController@schoolEmailVerifyUpdate');
});

Route::group(array('prefix' => 'school/'), function() {
	Route::post('account/auth/profile', 'SchoolProfileController@step1Update');
	Route::get('account/profile', 'Auth\AuthSchoolController@step1');	
	Route::get('account/review', 'Auth\AuthSchoolController@step2');	
	Route::get('account/payment', 'Auth\AuthSchoolController@step3');	
	Route::post('account/payment/pay', 'PaymentController@schoolFirst');	
	Route::get('review-confirmation', 'SchoolProfileController@reviewConfirmation');
	//Route::get('account/verify/hq', 'SchoolProfileController@schoolEmailVerifySecond');	
});

Route::group(array('prefix' => 'payment/'), function() {
	Route::get('confirm_payment', 'PaymentController@confirmPayment');
	Route::get('confirm_payment/{admissionId}/view', 'PaymentController@confirmPaymentView');
});

Route::group(array('prefix' => 'course/'), function() {
	Route::get('{course_hash}/details', 'CourseController@courseView');
	Route::get('eligibility/{linkId}/list', 'CourseController@eligibilityList');
	Route::post('eligibility/deleted', 'CourseController@eligibilityDelete');
	Route::post('eligibility/disabled', 'CourseController@eligibilityDisable');
	Route::post('eligibility/eligibilitystore', 'CourseController@eligibilityStore');

	Route::get('syllabus/{linkId}/list', 'CourseController@syllabusList');
	Route::post('syllabus/store', 'CourseController@syllabusStore');
	Route::post('syllabus/update', 'CourseController@syllabusUpdate');
	Route::post('syllabus/deleted', 'CourseController@syllabusDelete');
	
	Route::post('syllabus/disabled', 'CourseController@syllabusDisable');
	Route::post('tab1/update/{linkId}', 'CourseController@courseDetailsUpdate');
	Route::post('tab2/update/{linkId}', 'CourseController@eligibilityUpdate');
	Route::post('syllabus/update/{linkId}', 'CourseController@syllabusUpdate');
	Route::post('status', 'CourseController@status');
}); 

Route::group(array('prefix' => 'admission/'), function() {
	Route::get('status', 'AdmissionOpenController@admissionStatus');
	Route::get('transaction', 'AdmissionOpenController@transaction');

	Route::get('live_search/action', 'AdmissionOpenController@action')->name('live_search.action');

	Route::get('transactionapi', 'AdmissionOpenController@transactionapi');
	Route::get('transaction/{id}/view', 'AdmissionOpenController@transactionDetails');	
	Route::get('transaction/academicdetails', 'AdmissionOpenController@academicDetails');	
	Route::get('create/{linkId}', 'AdmissionOpenController@admissionOpen'); 
	Route::get('open/list', 'AdmissionOpenController@admissionCreateList'); 	
	Route::get('create/{id}/detail', 'AdmissionOpenController@admissionDetail');
	Route::get('detail/list/{id}', 'AdmissionOpenController@admissionDetailList');
	Route::post('open/update', 'AdmissionOpenController@admissionOpenUpdate'); 	
	Route::get('merit-list','AdmissionOpenController@meritList');
	Route::get('documents','AdmissionOpenController@admissionDocuments');
	Route::get('confirm','AdmissionOpenController@admissionConfirm');
	Route::get('confirm/d','AdmissionOpenController@admissionConfirmDetail');
	Route::post('documents/confirm','AdmissionOpenController@admissionDocumentsConformStatus');
	Route::post('documents/cancelled','AdmissionOpenController@admissionDocumentsCancelledStatus');
}); 

Route::group(array('prefix' => 'users/'), function() {
	Route::post('status', 'UserController@statusUser');
});

Route::group(array('prefix' => 'faculty/'), function() {
	Route::post('status', 'FacultyController@statusFaculty');
	Route::post('list', 'FacultyController@show');
	Route::post('deleted', 'FacultyController@deleteGallery');
	Route::post('disabled', 'FacultyController@disableGallery');
});

Route::group(array('prefix' => 'settings/'), function() {
	Route::get('security', 'SettingController@securityIndex');
	Route::get('privacy', 'SettingController@privacyIndex');
	Route::get('notifications', 'SettingController@notifications');
	Route::post('general/edit', 'SettingController@generalSettingEdit');
	Route::post('general/update', 'SettingController@generalSettingUpdate');
	Route::get('changePassword','HomeController@showChangePasswordForm');
	Route::post('changePassword','HomeController@changePassword')->name('changePassword');    
});

Route::group(array('prefix' => 'profile/'), function() {
	Route::post('update', 'ProfileController@update');	 	 
	Route::post('up/banner', 'ProfileController@schoolBannerImage');	 	 
	Route::post('up/logo', 'ProfileController@schooLogoImage');	 	 
}); 

Route::group(array('prefix' => 'enrolments/'), function() {
	Route::get('update', 'EnrolmentController@update');	 
	Route::get('enrollmentList', 'EnrolmentController@enrollmentList');	 
	Route::get('{courseid}/list', 'EnrolmentController@list');	 
	Route::get('{courseid}/listapi', 'EnrolmentController@listapi');	 
	Route::get('{courseid}/upload', 'EnrolmentController@upload');
	Route::get('{courseid}/{id}/edit', 'EnrolmentController@listEdit');
	Route::post('deleted', 'EnrolmentController@enrollmentDelete');	 
}); 

Route::group(array('prefix' => 'gallery/'), function() {
	Route::post('list', 'GalleryController@show');	 
	Route::post('upload', 'GalleryController@upload');	 
	Route::post('deleted', 'GalleryController@deleteGallery');	 
	Route::post('disabled', 'GalleryController@disableGallery');	 
}); 

Route::group(array('prefix' => 'enquiry/'), function() {
	Route::get('list', 'EnquiryController@show');	 
}); 

Route::group(array('prefix' => 'bank/'), function() {
	Route::get('list', 'BankController@list');	 
}); 

Route::resource('course', 'CourseController');
Route::resource('admission', 'AdmissionOpenController');
Route::resource('users', 'UserController');
Route::resource('enrolments', 'EnrolmentController');
Route::resource('roles', 'RoleController');
Route::resource('faculty', 'FacultyController');
Route::resource('permissions', 'PermissionController');
Route::resource('payments/ad', 'PaymentController');
Route::resource('bank', 'BankController');
Route::resource('all-activity', 'ActivityController');
Route::resource('settings', 'SettingController');
Route::resource('gallery', 'GalleryController');
Route::resource('profile', 'ProfileController');

Route::post('schoolDetailUpdate/update', 'SchoolController@schoolDetailUpdate')->name('home');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class RoleController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $roles = Role::all();//Get all roles

        return view('school.roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::all();//Get all permissions

        return view('admin.roles.create', ['permissions'=>$permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
    //Validate name and permissions field
        $this->validate($request, [
            'name'=>'required|unique:roles|max:10',
            'permissions' =>'required',
            ]
        );

        $name = $request['name'];
        $role = new Role();
        $role->name = $name;

        $permissions = $request['permissions'];

        $role->save();
    //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); 
         //Fetch the newly created role and assign permission
            $role = Role::where('name', '=', $name)->first(); 
            $role->givePermissionTo($p);
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' added!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('school.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id);//Get role with the given id
    //Validate name and permission fields
        $this->validate($request, [
            'name'=>'required|max:10|unique:roles,name,'.$id,
            'permissions' =>'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role'. $role->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
             'Role deleted!');
    }
}

app/Http/Controllers/SchoolController.php
<?php   
namespace App\Http\Controllers;
use Auth;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Model\TempSchoolProfile;
use App\Model\User;
use Session;
use DB;

class SchoolController extends Controller
{
   public function __construct(){

   	$this->middleware('auth');
   }
   
   public function index(){


      $userId = Auth::user()->id;  

      $schoolProfile = DB::table('temp_school_profile')
         ->join('users', 'temp_school_profile.user_id', '=', 'users.id')
         ->where('users.id',$userId)
         ->first();       

      return view('temp_school_profile',compact('schoolProfile'));
    }

   public function pendingSchoolIndex(){

      $userId = Auth::user()->id;
      
      $q = TempSchoolprofile::query();

      $q->whereHas('user', function($query) use ($userId) {
         $query->where('id', $userId);
         $query->where('user_status', getenv('STATUS_11'));
      });
      $q->with('state');

      $schoolData = $q->get()->toArray();

      return view('school.school_registration.index',compact('schoolData'));
   }

   public function pendingSchoolView(Request $request,$id){

      $userId = Auth::user()->id;
      
      $schoolData = TempSchoolProfile::with('state')->where('id',$id)->first()->toArray();
      return view('school.school_registration.view',compact('schoolData'));
   }

   public function activeSchoolIndex(){
      $userId = Auth::user()->id;
      $q = TempSchoolprofile::query();
      $q->whereHas('user', function($query) use ($userId) {
         $query->where('id', $userId);
         $query->where('user_status', getenv('STATUS_22'));
      });
      $q->with('state');
      $schoolData = $q->get()->toArray();
      return view('school.school_active.index',compact('schoolData'));
   }

   public function activeSchoolView(Request $request,$id){
      $userId = Auth::user()->id;
      $schoolData = TempSchoolProfile::with('state')->where('id',$id)->first()->toArray();
      return view('school.school_active.view',compact('schoolData'));
   }

   public function schoolApprove(Request $request){

      $userId = Auth::user()->id;

      $post = $request->all();     

      $data = User::where('id',$post['user_id'])->first();        

      $data->user_status = getenv('STATUS_22');

      $data->save();

      return redirect('pending-school')->with('success','School approved successfully')   ;

   }

}

resources/views/school/roles/create.blade.php
@extends('layouts.app')

@section('title', '| Add Role')

@section('content')
<section class="content" > 
<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Add Role</h1>
    <hr>

    {{ Form::open(array('url' => 'roles')) }}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>

    <h5><b>Assign Permissions</b></h5>

    <div class='form-group'>
        @foreach ($permissions as $permission)
            {{ Form::checkbox('permissions[]',  $permission->id ) }}
            {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>

        @endforeach
    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>
</section>
@endsection

resources/views/school/roles/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Role')

@section('content')
<section class="content" > 
<div class='col-lg-4 col-lg-offset-4'>
    <h1><i class='fa fa-key'></i> Edit Role: {{$role->name}}</h1>
    <hr>

    {{ Form::model($role, array('route' => array('roles.update', $role->id), 'method' => 'PUT')) }}

    <div class="form-group">
        {{ Form::label('name', 'Role Name') }}
        {{ Form::text('name', null, array('class' => 'form-control')) }}
    </div>

    <h5><b>Assign Permissions</b></h5>
    @foreach ($permissions as $permission)

        {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
        {{Form::label($permission->name, ucfirst($permission->name)) }}<br>

    @endforeach
    <br>
    {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}    
</div>
</section>
@endsection

resources/views/school/roles/index.blade.php
@extends('layouts.app')

@section('title', '| Roles')

@section('content')
<section class="content"> 
    <div class="row">                                                      
        <div class="offset-3 col-md-5">
            <div class="card my-5">
                <div class="card-body">
                    <div class="card-title mb-2"><i class="fa fa-key pr-2" aria-hidden="true"></i><strong>Roles</strong></div>  
                    <div class="">  
                        <div class="">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Role</th>
                                            <th>Permissions</th>                                        
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($roles as $role)
                                        <tr>
                                            <td>{{ $role->name }}</td>
                                            <td>{{ str_replace(array('[',']', '"'),' ', $role->permissions()->pluck('name')) }}</td>                             
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <a href="{{ url()->previous() }}" class="btn btn-sm btn-outline-secondary m-0">Back</a> 
                        </div>
                    </div>
                </div>
        </div>
    </div>
</section>
<!-- 

<section class="content mt-5" > 
<div class="col-lg-10 col-lg-offset-1">
    <h1><i class="fa fa-key"></i>&nbsp;Roles
    <a href="{{ route('users.index') }}" class="btn btn-primary btn-sm pull-right">Users</a>
    <a href="{{ route('permissions.index') }}" class="btn btn-primary btn-sm pull-right">Permissions</a></h1>
    <hr>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Role</th>
                    <th>Permissions</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($roles as $role)
                <tr>
                    <td>{{ $role->name }}</td>
                    <td>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')) }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}
                    <td>
                    <a href="{{ URL::to('roles/'.$role->id.'/edit') }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>
                    {!! Form::open(['method' => 'DELETE', 'route' => ['roles.destroy', $role->id] ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <a href="{{ URL::to('roles/create') }}" class="btn btn-success">Add Role</a>

</div>
</section> -->
@endsection